apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonset.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.daemonset.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ovs-cni
  updateStrategy:
    {{- toYaml .Values.daemonset.updateStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        tier: node
        app: ovs-cni
      annotations:
        {{- toYaml .Values.daemonset.annotations | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      hostNetwork: true
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      restartPolicy: {{ .Values.daemonset.restartPolicy }}
      terminationGracePeriodSeconds: {{ .Values.daemonset.terminationGracePeriodSeconds }}
      initContainers:
      - name: ovs-cni-plugin
        image: "{{ .Values.initImage.repository }}/{{ .Values.initImage.name }}:{{ .Values.initImage.tag }}"
        command: ["/bin/sh","-c"]
        args:
          - >
            cp /ovs /host{{ .Values.cniMountPath }}/ovs &&
            cp /ovs-mirror-producer /host{{ .Values.cniMountPath }}/ovs-mirror-producer &&
            cp /ovs-mirror-consumer /host{{ .Values.cniMountPath }}/ovs-mirror-consumer
        imagePullPolicy: {{ .Values.initImage.pullPolicy }}
        securityContext:
          privileged: true
        resources:
          requests:
            {{- toYaml .Values.resources.init.requests | nindent 12 }}
          limits:
            {{- toYaml .Values.resources.init.limits | nindent 12 }}
        volumeMounts:
        - name: cnibin
          mountPath: /host{{ .Values.cniMountPath }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
      - name: ovs-cni-marker
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        command:
          - /marker
        args:
          - -v
          - "{{ .Values.marker.verbosity }}"
          - -logtostderr
          - -node-name
          - $(NODE_NAME)
          - -ovs-socket
          - unix:/host{{ .Values.varRunPath }}/{{ .Values.dbSocketName }}
          - -healthcheck-interval={{ .Values.marker.healthcheckInterval }}
        volumeMounts:
          - name: ovs-var-run
            mountPath: /host{{ .Values.varRunPath }}
        resources:
          requests:
            {{- toYaml .Values.resources.marker.requests | nindent 12 }}
          limits:
            {{- toYaml .Values.resources.marker.limits | nindent 12 }}
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - >-
                find /tmp/healthy -mmin -2 | grep -q '/tmp/healthy'
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - >-
                find /tmp/healthy -mmin -2 | grep -q '/tmp/healthy'
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        terminationMessagePolicy: FallbackToLogsOnError
      volumes:
        - name: cnibin
          hostPath:
            path: {{ .Values.cniMountPath }}
        - name: ovs-var-run
          hostPath:
            path: {{ .Values.varRunPath }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
